class Dataingestionartifact:
    pass
class datavalidationartifact:...
class datatransformationartifact:...
class modeltrainerartifact:...
class modelvaluatingartifact:...
class modelpusherartifact:...